### ISSUE TITLE
Frozen columns - overlap on hover

### ISSUE THREAD

**Issue by poison4o** [vaadin/flow-components#3554]
### Description of the bug

If you have a frozen column(s), and you have some other column(s) under the frozen, on hover the row, the value of the back column(s) overlap the value of the frozen column(s). This is also tested with the latest version of vaadin 14.8.14

### Expected behavior

The value of the column(s) that is under the frozen column(s) shouldn`t be visible

### Minimal reproducible example

When you have a frozen column, and you want to scroll(horizontal scroll), the other columns will go under the frozen column(s), which is fine but when you just hover the row, you will see that the value that is under frozen column(s) is showing.
You can check the [https://postimg.cc/GHYK5SrK](https://postimg.cc/GHYK5SrK)

### Versions

- Vaadin / Flow version: 14.8.6
- Java version:  11
- OS version: windows 11
- Browser version (if applicable): Brave v1.41.100
- Application Server (if applicable): spring-boot-starter-parent 2.6.6
- IDE (if applicable): Intellij 2022.1.2 (Community Edition)

**Comment by poison4o** [comment]
https://user-images.githubusercontent.com/3823186/183657226-08800d8b-a787-4b04-85d1-b37ae378d470.mp4

You can see the uploaded video, so currently i\`m using 14.8.6, but i have mentioned 14.8.14 because i switched to it just to check whether i\`ll have the same behavior, and i have it. So i\`m using `Grid`. The cells are not editable.

**Comment by poison4o** [comment]
So the problem is on my side, i found out, that there is a custom css which is causing the problem, so the issue is fixed

**Comment by Frettman** [comment]
The problem is triggered when a frozen column overlaps with another column and both (or maybe just the frozen is enough) have a semi-transparent background color. This is still an issue in Vaadin 25.2. The only example I found in the [documentation](https://vaadin.com/docs/latest/components/grid/styling) also uses a background color with an alpha value which works fine as long as no column is frozen. The only workaround I could find so far was using this as `background`, when e.g. `--lumo-error-color-50pct` is the color you want:
```css
background: linear-gradient(var(--lumo-error-color-50pct), var(--lumo-error-color-50pct)), var(--lumo-base-color);
```
Not particularly pretty, but it seems to work. I also tried `color-mix(...)`, but when one input color has an alpha, so does the result.
