### ISSUE TITLE
Display issue with ComboBox.setItems(query) when dragging scrollbar page element

### ISSUE THREAD

**Issue by guttormvik2** [vaadin/flow-components#6036]
### Describe the bug

When I open up a ComboBox with 50+ items, provided by setItems(query), it displays the 50 first items, and a scrollbar.
Since the total size is unknown, the scrollbar page element is small.
When I drag the scrollbar page element down, beyond the total number of actual rows, I get an empty page, and the scrollbar page element disappears.

### Expected-behavior

I think I understand why this is a problem, and why it can be hard to find a generic solution.

For my needs however, I have a suggestion.
I don't see the point of displaying a list of "millions of rows", and allow user to scroll through. If there are that many rows, the user has to narrow it down.
So, how about *never* fetching more than the first pagesize+1 filtered rows
If you get back pagesize+1, don't display the last row. Instead show an unselectable "..."
The user then has to write more in the filter.

I will probably work around this issue by increasing the pagesize to 200. Very few of our queries are allowed to return more than that.

### Reproduction

    // More than 50 rows
    private List<Person> persons = java.util.List.of
        ( new Person(218027, "Aanestad", "Alexander Anderl")
        , new Person(656081, "Aanestad", "Andreas")
        ...
        );

    public ComboBoxTest() {

        var nextOfKin = new ComboBox<Person>("Next of Kin");
        nextOfKin.setAutoOpen(false);
        nextOfKin.setAllowCustomValue(true);
        nextOfKin.setItemLabelGenerator(Person::displayText);

        var renderer = LitRenderer.<Person>of("<b>${item.lastName}</b>, ${item.firstName}")
            .withProperty("lastName", Person::lastName)
            .withProperty("firstName", Person::firstName);

        nextOfKin.setRenderer(renderer);

        nextOfKin.setItems(query -> {
            String filter = query.getFilter().orElse(null);
            return persons
                .stream()
                .filter(p-> filter==null ? true : p.displayText().toLowerCase().contains(filter))
                .skip(query.getOffset())
                .limit(query.getLimit());
        });

        add(nextOfKin);

    }

### System Info

Windows 10, Firefox 122, Vaadin 24.3.0

**Comment by yuriy-fix** [comment]
Dear @guttormvik2, could you please provide a screenshot / recording of the scrollbar state?
What Vaadin version are you using?

**Comment by guttormvik2** [comment]
@yuriy-fix:

Combobox when opened the first time. Since it doesn't know how many rows there are, the scroll element is tiny:
![image](https://github.com/vaadin/flow-components/assets/108350446/1a224653-6219-4e01-9ef5-135bcec80f49)

Scrolling past the last row. The scoll element has jumped to the end, but my mouse pointer is somewhere in the middle of the scrollbar:
![image](https://github.com/vaadin/flow-components/assets/108350446/13eb2e55-b675-4d61-b28a-fcc7f4e0e552)

Scrolled past all rows:
![image](https://github.com/vaadin/flow-components/assets/108350446/71fc7db2-cbe7-4a01-a7ff-115283254065)

**Comment by guttormvik2** [comment]
Bonus issue:
If I reopen the ComboBox it knows the total size:
![image](https://github.com/vaadin/flow-components/assets/108350446/25091d76-3204-4e61-ac20-5a3439d858e7)

If I drag the scroll-element to the end, it stops just before the last row:
![image](https://github.com/vaadin/flow-components/assets/108350446/105e08b9-02e9-4fe9-ab84-0f290ebac358)

Clicking the scrollbar 'down' button, I can still reach it:
![image](https://github.com/vaadin/flow-components/assets/108350446/a57ac572-0d21-4235-bec4-2b1069e94647)

**Comment by guttormvik2** [comment]
Btw; All the names in those screenshots, except mine, are obfuscated

**Comment by yuriy-fix** [comment]
Thank you for providing screenshots!

**Comment by vursen** [comment]
I was able to reproduce the issue on Windows with Firefox 122, but not with Firefox 123, which suggests that it's likely a browser bug that has been fixed. Could you please confirm? @guttormvik2

**Comment by guttormvik2** [comment]
@vursen, looks like you're right. With Vaadin 24.3.6 and Firefox 123.01 and it behaves better. With Chrome there is no issue.

With Firefox, I still have the minor issue that the 2nd time I open the ComboBox, I'm not able to drag the scroller to the bottom. It stops 1-2 items above, but if release the mouse, and then grab the scroller again, I can scroll to the last items.

**Comment by vursen** [comment]
> With Firefox, I still have the minor issue that the 2nd time I open the ComboBox, I'm not able to drag the scroller to the bottom. It stops 1-2 items above, but if release the mouse, and then grab the scroller again, I can scroll to the last items.

Weird, I'm not able to reproduce this with Browserstack:

https://github.com/vaadin/flow-components/assets/5039436/3b064b39-f84e-4a76-a679-6f6d5b887531

I'm using this snippet that I created from your example. Could it be missing something?

```java
public static class Person {
    private int id;
    private String name;

    public Person(int id, String name) {
        this.id = id;
        this.name = name;
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }
}

private List<Person> persons = IntStream.range(0, 100)
        .mapToObj(i -> new Person(i, "Item " + i))
        .collect(Collectors.toList());

public ComboBoxView() {
    ComboBox<Person> comboBox = new ComboBox<>("Next of Kin");
    comboBox.setItemLabelGenerator(Person::getName);

    LitRenderer renderer = LitRenderer.<Person>of("${item.name}").withProperty("name", Person::getName);
    comboBox.setRenderer(renderer);

    comboBox.setItems(query -> {
        String filter = query.getFilter().orElse(null);
        return persons
                .stream()
                .filter(p -> filter == null ? true : p.getName().toLowerCase().contains(filter))
                .skip(query.getOffset())
                .limit(query.getLimit());
    });

    add(comboBox);
}
```

**Comment by yuriy-fix** [comment]
Closing as stale. Dear @guttormvik2, feel free to re-open of still valid.
